<?php
// Выборка по фильтру из инфоблока
// что делать когда arFilter не фильтрует
// включаем  "USE_FILTER" => "Y",

$code = array();
foreach($arResult['DISPLAY_PROPERTIES'] as $key => $value) {
    $code['PROPERTY_TOUR_'.$key.'_VALUE'] = $value["VALUE"];
}
global $arrFilter;
$arrFilter = array($code);
?>
<?if($arrFilter[0]):?>
    <?$APPLICATION->IncludeComponent(
        "bitrix:catalog",
        "tours",
        Array(
            "ACTION_VARIABLE" => "action",
            "ADD_ELEMENT_CHAIN" => "Y",
            "ADD_PICT_PROP" => "-",
            "ADD_PROPERTIES_TO_BASKET" => "N",
            "ADD_SECTIONS_CHAIN" => "Y",
            "AJAX_MODE" => "N",
            "AJAX_OPTION_ADDITIONAL" => "",
            "AJAX_OPTION_HISTORY" => "N",
            "AJAX_OPTION_JUMP" => "N",
            "AJAX_OPTION_STYLE" => "Y",
            "AJAX_TYPE" => "ZAKAZ",
            "BASKET_URL" => "",
            "CACHE_FILTER" => "N",
            "CACHE_GROUPS" => "Y",
            "CACHE_TIME" => "36000000",
            "CACHE_TYPE" => "A",
            "COMPATIBLE_MODE" => "Y",
            "COMPONENT_TEMPLATE" => "tours",
            "COMPOSITE_FRAME_MODE" => "A",
            "COMPOSITE_FRAME_TYPE" => "AUTO",
            "DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
            "DETAIL_BACKGROUND_IMAGE" => "-",
            "DETAIL_BRAND_USE" => "N",
            "DETAIL_BROWSER_TITLE" => "-",
            "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
            "DETAIL_DETAIL_PICTURE_MODE" => "MAGNIFIER",
            "DETAIL_DISPLAY_NAME" => "Y",
            "DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
            "DETAIL_IMAGE_RESOLUTION" => "16by9",
            "DETAIL_META_DESCRIPTION" => "-",
            "DETAIL_META_KEYWORDS" => "-",
            "DETAIL_PAGE_TABS_SORT" => "DESC_INFO",
            "DETAIL_PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
            "DETAIL_PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
            "DETAIL_SET_CANONICAL_URL" => "N",
            "DETAIL_SHOW_POPULAR" => "Y",
            "DETAIL_SHOW_SLIDER" => "N",
            "DETAIL_SHOW_VIEWED" => "Y",
            "DETAIL_STRICT_SECTION_CHECK" => "N",
            "DETAIL_USE_COMMENTS" => "N",
            "DETAIL_USE_TABS" => "Y",
            "DETAIL_USE_VOTE_RATING" => "N",
            "DISABLE_INIT_JS_IN_COMPONENT" => "N",
            "DISPLAY_BOTTOM_PAGER" => "N",
            "DISPLAY_TOP_PAGER" => "N",
            "ELEMENT_SORT_FIELD" => "sort",
            "ELEMENT_SORT_FIELD2" => "id",
            "ELEMENT_SORT_ORDER" => "asc",
            "ELEMENT_SORT_ORDER2" => "desc",
            "FILTER_FIELD_CODE" => array(0=>"",1=>"",),
            "FILTER_HIDE_ON_MOBILE" => "N",
            "FILTER_NAME" => "arrFilter",
            "FILTER_PRICE_CODE" => "",
            "FILTER_PROPERTY_CODE" => array(0=>"TOUR_SUB_HEAD",1=>"",),
            "FILTER_VIEW_MODE" => "VERTICAL",
            "HIDE_IF_SUBSECTIONS_EXISTS" => "N",
            "IBLOCK_ID" => "21",
            "IBLOCK_TYPE" => "tours_s1",
            "INCLUDE_SUBSECTIONS" => "Y",
            "INSTANT_RELOAD" => "N",
            "LABEL_PROP" => "-",
            "LABEL_PROP_MOBILE" => "",
            "LABEL_PROP_POSITION" => "top-left",
            "LAZY_LOAD" => "N",
            "LINE_ELEMENT_COUNT" => "3",
            "LINK_ELEMENTS_URL" => "",
            "LINK_IBLOCK_ID" => "",
            "LINK_IBLOCK_TYPE" => "",
            "LINK_PROPERTY_SID" => "",
            "LINK_TO_AJAX" => "",
            "LIST_BROWSER_TITLE" => "-",
            "LIST_ENLARGE_PRODUCT" => "STRICT",
            "LIST_META_DESCRIPTION" => "-",
            "LIST_META_KEYWORDS" => "-",
            "LIST_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
            "LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
            "LIST_PROPERTY_CODE_MOBILE" => "",
            "LIST_SHOW_SLIDER" => "Y",
            "LIST_SLIDER_INTERVAL" => "3000",
            "LIST_SLIDER_PROGRESS" => "N",
            "LOAD_ON_SCROLL" => "N",
            "MESSAGE_404" => "",
            "MESS_BTN_ADD_TO_BASKET" => "",
            "MESS_BTN_BUY" => "",
            "MESS_BTN_COMPARE" => "",
            "MESS_BTN_DETAIL" => "",
            "MESS_BTN_SUBSCRIBE" => "Подписаться",
            "MESS_NOT_AVAILABLE" => "",
            "PAGER_BASE_LINK_ENABLE" => "N",
            "PAGER_DESC_NUMBERING" => "N",
            "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
            "PAGER_SHOW_ALL" => "N",
            "PAGER_SHOW_ALWAYS" => "N",
            "PAGER_TEMPLATE" => ".default",
            "PAGER_TITLE" => "",
            "PAGE_ELEMENT_COUNT" => "30",
            "PARTIAL_PRODUCT_PROPERTIES" => "N",
            "PRICE_CODE" => array(),
            "PRICE_VAT_INCLUDE" => "Y",
            "PRICE_VAT_SHOW_VALUE" => "N",
            "PRODUCT_ID_VARIABLE" => "id",
            "PRODUCT_PROPS_VARIABLE" => "prop",
            "PRODUCT_QUANTITY_VARIABLE" => "quantity",
            "SEARCH_CHECK_DATES" => "Y",
            "SEARCH_NO_WORD_LOGIC" => "Y",
            "SEARCH_PAGE_RESULT_COUNT" => "50",
            "SEARCH_RESTART" => "N",
            "SEARCH_USE_LANGUAGE_GUESS" => "Y",
            "SECTIONS_SHOW_PARENT_NAME" => "Y",
            "SECTIONS_VIEW_MODE" => "LIST",
            "SECTION_BACKGROUND_IMAGE" => "-",
            "SECTION_COUNT_ELEMENTS" => "N",
            "SECTION_HIDE_ICONLIST" => "N",
            "SECTION_HIDE_PREVIEW_TEXT" => "N",
            "SECTION_ID_VARIABLE" => "SECTION_ID",
            "SECTION_TOP_DEPTH" => "2",
            "SECTION_USE_IMAGE_RESIZE" => "N",
            "SEF_FOLDER" => "/iran-tour/",
            "SEF_MODE" => "Y",
            "SEF_URL_TEMPLATES" => array("sections"=>"/iran-tour/","section"=>"#SECTION_CODE#/","element"=>"#SECTION_CODE#/#ELEMENT_CODE#/","compare"=>"","smart_filter"=>"#SECTION_CODE#/filter/#SMART_FILTER_PATH#/apply/",),
            "SET_LAST_MODIFIED" => "N",
            "SET_STATUS_404" => "N",
            "SET_TITLE" => "Y",
            "SHOW_404" => "N",
            "SHOW_ADDITIONAL_PANEL" => "N",
            "SHOW_DEACTIVATED" => "N",
            "SHOW_PRICE_COUNT" => "1",
            "SHOW_SKU_DESCRIPTION" => "N",
            "SHOW_TOP_ELEMENTS" => "N",
            "SIDEBAR_DETAIL_SHOW" => "N",
            "SIDEBAR_PATH" => "",
            "SIDEBAR_SECTION_SHOW" => "N",
            "TEMPLATE_THEME" => "blue",
            "TOP_ELEMENT_COUNT" => "9",
            "TOP_ELEMENT_SORT_FIELD" => "sort",
            "TOP_ELEMENT_SORT_FIELD2" => "id",
            "TOP_ELEMENT_SORT_ORDER" => "asc",
            "TOP_ELEMENT_SORT_ORDER2" => "desc",
            "TOP_LINE_ELEMENT_COUNT" => "3",
            "TOP_VIEW_MODE" => "SECTION",
            "USER_CONSENT" => "N",
            "USER_CONSENT_ID" => "0",
            "USER_CONSENT_IS_CHECKED" => "Y",
            "USER_CONSENT_IS_LOADED" => "N",
            "USE_COMPARE" => "N",
            "USE_ELEMENT_COUNTER" => "N",
            "USE_ENHANCED_ECOMMERCE" => "N",
            "USE_FILTER" => "Y",
            "USE_MAIN_ELEMENT_SECTION" => "N",
            "USE_PRICE_COUNT" => "N",
            "USE_PRODUCT_QUANTITY" => "N",
            "USE_REVIEW" => "N",
            "USE_STORE" => "N"
        )
    );?>
<?endif;?>
